// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/zeid/service.proto

/*
Package zeid is a generated protocol buffer package.

It is generated from these files:
	rpc/zeid/service.proto

It has these top-level messages:
	Activity
	ListActivitiesReq
	ListActivitiesResp
	CurrentActivityReq
	CurrentActivityResp
	AssignActivityReq
	AssignActivityResp
*/
package zeid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Activity struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Color       string `protobuf:"bytes,3,opt,name=color" json:"color,omitempty"`
	Integration string `protobuf:"bytes,4,opt,name=integration" json:"integration,omitempty"`
	DeviceSide  int64  `protobuf:"varint,5,opt,name=device_side,json=deviceSide" json:"device_side,omitempty"`
}

func (m *Activity) Reset()                    { *m = Activity{} }
func (m *Activity) String() string            { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()               {}
func (*Activity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Activity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Activity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Activity) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Activity) GetIntegration() string {
	if m != nil {
		return m.Integration
	}
	return ""
}

func (m *Activity) GetDeviceSide() int64 {
	if m != nil {
		return m.DeviceSide
	}
	return 0
}

type ListActivitiesReq struct {
}

func (m *ListActivitiesReq) Reset()                    { *m = ListActivitiesReq{} }
func (m *ListActivitiesReq) String() string            { return proto.CompactTextString(m) }
func (*ListActivitiesReq) ProtoMessage()               {}
func (*ListActivitiesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListActivitiesResp struct {
	Activities        []*Activity `protobuf:"bytes,1,rep,name=activities" json:"activities,omitempty"`
	CurrentActivityId string      `protobuf:"bytes,2,opt,name=current_activity_id,json=currentActivityId" json:"current_activity_id,omitempty"`
}

func (m *ListActivitiesResp) Reset()                    { *m = ListActivitiesResp{} }
func (m *ListActivitiesResp) String() string            { return proto.CompactTextString(m) }
func (*ListActivitiesResp) ProtoMessage()               {}
func (*ListActivitiesResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListActivitiesResp) GetActivities() []*Activity {
	if m != nil {
		return m.Activities
	}
	return nil
}

func (m *ListActivitiesResp) GetCurrentActivityId() string {
	if m != nil {
		return m.CurrentActivityId
	}
	return ""
}

type CurrentActivityReq struct {
}

func (m *CurrentActivityReq) Reset()                    { *m = CurrentActivityReq{} }
func (m *CurrentActivityReq) String() string            { return proto.CompactTextString(m) }
func (*CurrentActivityReq) ProtoMessage()               {}
func (*CurrentActivityReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CurrentActivityResp struct {
	Activity  *Activity `protobuf:"bytes,1,opt,name=activity" json:"activity,omitempty"`
	StartTime string    `protobuf:"bytes,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	IsIdle    bool      `protobuf:"varint,3,opt,name=is_idle,json=isIdle" json:"is_idle,omitempty"`
}

func (m *CurrentActivityResp) Reset()                    { *m = CurrentActivityResp{} }
func (m *CurrentActivityResp) String() string            { return proto.CompactTextString(m) }
func (*CurrentActivityResp) ProtoMessage()               {}
func (*CurrentActivityResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CurrentActivityResp) GetActivity() *Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

func (m *CurrentActivityResp) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CurrentActivityResp) GetIsIdle() bool {
	if m != nil {
		return m.IsIdle
	}
	return false
}

type AssignActivityReq struct {
	ActivityId string `protobuf:"bytes,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
}

func (m *AssignActivityReq) Reset()                    { *m = AssignActivityReq{} }
func (m *AssignActivityReq) String() string            { return proto.CompactTextString(m) }
func (*AssignActivityReq) ProtoMessage()               {}
func (*AssignActivityReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AssignActivityReq) GetActivityId() string {
	if m != nil {
		return m.ActivityId
	}
	return ""
}

type AssignActivityResp struct {
}

func (m *AssignActivityResp) Reset()                    { *m = AssignActivityResp{} }
func (m *AssignActivityResp) String() string            { return proto.CompactTextString(m) }
func (*AssignActivityResp) ProtoMessage()               {}
func (*AssignActivityResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*Activity)(nil), "zei.zeid.Activity")
	proto.RegisterType((*ListActivitiesReq)(nil), "zei.zeid.ListActivitiesReq")
	proto.RegisterType((*ListActivitiesResp)(nil), "zei.zeid.ListActivitiesResp")
	proto.RegisterType((*CurrentActivityReq)(nil), "zei.zeid.CurrentActivityReq")
	proto.RegisterType((*CurrentActivityResp)(nil), "zei.zeid.CurrentActivityResp")
	proto.RegisterType((*AssignActivityReq)(nil), "zei.zeid.AssignActivityReq")
	proto.RegisterType((*AssignActivityResp)(nil), "zei.zeid.AssignActivityResp")
}

func init() { proto.RegisterFile("rpc/zeid/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x86, 0x65, 0x0c, 0xd4, 0x0c, 0x12, 0x15, 0x03, 0x6a, 0x2d, 0x5a, 0x54, 0xcb, 0x27, 0x4e,
	0x46, 0xa2, 0x7d, 0x01, 0xda, 0x13, 0x6a, 0xd5, 0x83, 0xdb, 0x13, 0x17, 0xcb, 0xf1, 0x8e, 0xd0,
	0x48, 0x60, 0x3b, 0xbb, 0x1b, 0x14, 0x90, 0x72, 0xce, 0xe3, 0xe6, 0x15, 0x22, 0x2f, 0x36, 0x31,
	0x38, 0xc9, 0xcd, 0xfe, 0x66, 0xc7, 0xfa, 0xfe, 0x7f, 0x65, 0xf8, 0x24, 0xf3, 0x64, 0x7e, 0x24,
	0x16, 0x73, 0x45, 0x72, 0xcf, 0x09, 0x05, 0xb9, 0xcc, 0x74, 0x86, 0xce, 0x91, 0x38, 0x28, 0xb8,
	0xff, 0x68, 0x81, 0xb3, 0x4c, 0x34, 0xef, 0x59, 0x1f, 0x70, 0x00, 0x2d, 0x16, 0xae, 0xe5, 0x59,
	0xb3, 0x5e, 0xd8, 0x62, 0x81, 0x08, 0xed, 0x34, 0xde, 0x91, 0xdb, 0x32, 0xc4, 0x3c, 0xe3, 0x18,
	0x3a, 0x49, 0xb6, 0xcd, 0xa4, 0x6b, 0x1b, 0x78, 0x7a, 0x41, 0x0f, 0xfa, 0x9c, 0x6a, 0xda, 0xc8,
	0x58, 0x73, 0x96, 0xba, 0x6d, 0x33, 0xab, 0x23, 0xfc, 0x06, 0x7d, 0x41, 0x85, 0x42, 0xa4, 0x58,
	0x90, 0xdb, 0xf1, 0xac, 0x99, 0x1d, 0xc2, 0x09, 0xfd, 0x63, 0x41, 0xfe, 0x08, 0x86, 0x7f, 0x58,
	0xe9, 0x52, 0x86, 0x49, 0x85, 0x74, 0xeb, 0xdf, 0x03, 0x5e, 0x43, 0x95, 0xe3, 0x02, 0x20, 0x3e,
	0x13, 0xd7, 0xf2, 0xec, 0x59, 0x7f, 0x81, 0x41, 0x95, 0x29, 0xa8, 0xf2, 0x84, 0xb5, 0x53, 0x18,
	0xc0, 0x28, 0xb9, 0x93, 0x92, 0x52, 0x1d, 0x95, 0xf4, 0x10, 0xb1, 0x28, 0xa3, 0x0d, 0xcb, 0x51,
	0xb5, 0xb9, 0x12, 0xfe, 0x18, 0xf0, 0xd7, 0x25, 0x2c, 0x7c, 0x1e, 0x60, 0xd4, 0xa0, 0x2a, 0xc7,
	0x00, 0x9c, 0xea, 0xa3, 0xa6, 0xbe, 0xd7, 0x75, 0xce, 0x67, 0x70, 0x0a, 0xa0, 0x74, 0x2c, 0x75,
	0xa4, 0xf9, 0x5c, 0x6f, 0xcf, 0x90, 0xff, 0xbc, 0x23, 0xfc, 0x0c, 0x1f, 0x58, 0x45, 0x2c, 0xb6,
	0x64, 0x5a, 0x76, 0xc2, 0x2e, 0xab, 0x95, 0xd8, 0x92, 0xff, 0x03, 0x86, 0x4b, 0xa5, 0x78, 0x93,
	0xd6, 0x9c, 0x8a, 0x66, 0xeb, 0x89, 0x4e, 0xd7, 0x57, 0x45, 0x2f, 0xa3, 0x5c, 0x6f, 0xa9, 0x7c,
	0xf1, 0x64, 0x81, 0xbd, 0x26, 0xc6, 0xdf, 0x30, 0xb8, 0xac, 0x18, 0xbf, 0xbc, 0xb8, 0x37, 0x6e,
	0x64, 0xf2, 0xf5, 0xed, 0xa1, 0xca, 0xf1, 0x2f, 0x7c, 0xbc, 0xea, 0x07, 0x6b, 0x0b, 0xcd, 0x42,
	0x27, 0xd3, 0x77, 0xa6, 0x2a, 0x2f, 0xe4, 0x2e, 0xd5, 0xeb, 0x72, 0x8d, 0x2a, 0xea, 0x72, 0xcd,
	0xc4, 0x3f, 0xbb, 0xeb, 0x76, 0x31, 0xba, 0xe9, 0x9a, 0x9f, 0xe0, 0xfb, 0x73, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x29, 0x60, 0x9b, 0x77, 0x1e, 0x03, 0x00, 0x00,
}
