name: zei
version: 0.1
summary: Timeular ZEI client.
description: |
  Timeular ZEI client and tools.
icon: icon.png

grade: devel
confinement: devmode

parts:
  go:
    source-tag: go1.10.1
  zei:
    after: [go, desktop-gtk3]
    plugin: go
    source: .
    go-packages:
      - github.com/pauldub/zei/cmd/zei
      - github.com/pauldub/zei/cmd/zeid
      - github.com/pauldub/zei/cmd/zei-tray
    go-importpath: github.com/pauldub/zei
    build-packages:
      - libgtk-3-dev
      - libappindicator3-dev
    stage-packages:
      - libappindicator3-1
    #  - libc6
  snappy-bins:
    plugin: shell
    shell: bash
    shell-flags: ['-ex']
    shell-command: |
      install -d "$SNAPCRAFT_PART_INSTALL/bin"
      install -t "$SNAPCRAFT_PART_INSTALL/bin" "$SNAPDIR"/bin/*

apps:
  zei:
    command: bin/zei
    plugs: [network]
  zei-tray:
    command: desktop-launch "$SNAP/bin/zei-tray"
    plugs: [network, x11, desktop]
  zeid:
    command: start_zeid.sh
    daemon: simple
    plugs: [bluetooth-control, bluez, network, network-bind]
    restart-condition: always
    sockets:
      rpc:
        listen-stream: 8594

hooks:
  configure:
    plugs: []
